### PR TITLE
Fix worldgen

### PR DESCRIPTION
**Pull request by dlkulp**
## Overview

Always wanted to get this game actually functional. The old worldgen was really bad and left the game generally unplayable. Though this is actually a complete rewrite of the entire game, (almost) all of the text was kept identical, the commands were kept identical (though a few more were added such as the previously unimplemented stealth), and the world generation was fixed so the game is actually playable. There's also a dev command to show a map overlay which really helped for testing.

All in all, I'm really happy with how this turned out and it feels (to me at least) like what we were originally intending to create.

## Testing

To test this, simply run `npm start` and browsersync should automatically start up the game and open a browser tab to play it. To test, all the commands should be functional, movement should work, enemies should have turns, you should lose if you run out of health and win if both terrorists in with the hostages are cleared.

Run `dev map` in game to see the map which makes it really easy to locate enemies, find the hostages, and navigate the building.

See a production build (minified with express server) using `npm run prod`. This should play identically to dev but on port 4000 instead of 3000 and doesn't have any kind of hot-reloading.

## Final Note

I created a branch called "original" to keep our old code intact and easily discoverable should we want to have access to it at some point. I have tried very hard to be as faithful to the original as possible with the new version which is why I feel comfortable merging this into master. Let me know if you have any questions or concerns, or if there's anyone else that should be added to the credits since I honestly can't remember who else was on this project.

### CODE REVIEW

**Comment by puregarlic** [comment]
Thanks for doing this--I'm excited to clone it and give it a look again. I think the only other collaborator was @Merfoo, since this was that Codeday at Catlin Gabel. Once this PR gets merged, I'll set up hosting so we can actually point friends/family to a playable version.

In terms of reviewing this PR, how in-depth do you want me to go? Do you want me to do an actual code review?

**Comment by dlkulp** [comment]
I mean, you're certainly welcome to give it a full code review of you have the time and desire to do so. If not, probably just playing it and verifying things with the map will make sure I didn't miss anything glaring.

I'm also open to comments and suggestions of there's anything else you think should be added or improved. Also feel free to make code changes directly if you feel comfortable doing that.

Thanks for taking a look at this!

**Comment by dlkulp** [comment]
Also, does @Merfoo have access to this repo?

**Comment by Merfoo** [comment]
Quite the throwback 😅 
I'd be interested to see what an actual code review from @puregarlic is like as well 👀

**Comment by dlkulp** [comment]
@puregarlic Speaking of hosting, I could theoretically set this up to use github's hosting if that would be easier.

**Comment by puregarlic** [comment]
> @puregarlic Speaking of hosting, I could theoretically set this up to use github's hosting if that would be easier.

If that's not too difficult, that would be appreciated. Otherwise, I'll just throw it on Vercel or Netlify

**Comment by puregarlic** [comment]
I'll take a note to do a full code review--I'll probably get around to it this weekend

**Comment by dlkulp** [comment]
> > @puregarlic Speaking of hosting, I could theoretically set this up to use github's hosting if that would be easier.
> 
> If that's not too difficult, that would be appreciated. Otherwise, I'll just throw it on Vercel or Netlify

I just set up a different repo using GitHub Pages so it shouldn't be too hard. They let you run actions which makes compiling TS, minifying, bundling, etc. pretty easy. Only downsides are static files and a silly URL, but neither are probably much of an issue.

**Comment by puregarlic** [comment]
@dlkulp let's do that then, let me know if there's anything I need to enable in the repository settings if you don't have access.

**Comment by dlkulp** [comment]
@puregarlic Sounds good! I'll get on that when this PR is merged. It'll probably take a commit or two just to make sure everything is functioning properly.

**Comment by dlkulp** [comment]
@puregarlic not to pester, but any updates? Don't feel pressured to put any more time into this than _you_ want. A quick clone and run would be fine or we could even just merge it since we don't exactly have a large player-base to annoy 😛

Whatever you have time for is fine!

**Comment by dlkulp** [comment]
Given the timeframe here, I'll just merge this and get it hosted. If anyone is interested in playing through things and looking for problems, by all means do so. I'd be more than willing to address issues found, otherwise it'll at least be out there for people to see. After I get hosting set up, it should be live [here](https://gl0vgames.github.io/McClaneSim/).  Thanks y'all!

**Comment by puregarlic** [comment]
@dlkulp totally slipped my radar 😞 thanks for merging this in 🙏🏼

**Pull request merged**
